name: podcastindex_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  crypto: ^3.0.6
  http: ^1.2.2
  convert: ^3.1.2
  collection: ^1.19.1
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.12

